version: "3.3"

networks:
  traefik-proxy:
    external:
      name: traefik-proxy

services:
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    container_name: traefik-forward-auth
    networks:
      - traefik-proxy
    environment:
      - DEFAULT_PROVIDER=generic-oauth
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://${GITEA_TRAEFIK_HOST}/login/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://${GITEA_TRAEFIK_HOST}/login/oauth/access_token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=https://${GITEA_TRAEFIK_HOST}/api/v1/user
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=${GITEA_OAUTH_CLIENT_ID}
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=${GITEA_OAUTH_CLIENT_SECRET}
      - PROVIDERS_GENERIC_OAUTH_TOKEN_STYLE=query
      - AUTH_HOST=${TRAEFIK_FORWARD_AUTH_HOST}
      - SECRET=${TRAEFIK_FORWARD_AUTH_SECRET}
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`${TRAEFIK_FORWARD_AUTH_HOST}`)"
      - "traefik.http.routers.traefik-forward-auth.entrypoints=websecure"
      - "traefik.http.routers.traefik-forward-auth.tls.certresolver=${ACME_CERT_RESOLVER}"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardAuth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardAuth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth@docker"

volumes:
  data:
  config:
